### ISSUE TITLE
Generate URL at the beginning of the upload.

### ISSUE THREAD

**Issue by HT-7** [pomf/pomf#162]
Problem: The user has to wait for the upload to finish before getting the URL.

Please generate the URL at the beginning of the upload. Discard it if the upload fails.

**Comment by nokonoko** [comment]
No... Since the file validation is server-side we cannot generate a URL before the file has been uploaded, thus there is no reason to generate it beforehand, it's actually quite stupid to waste resources on the server-side for a upload that might not complete.

Also this project has been superseded by https://github.com/nokonoko/uguu, can you read?
