### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by vc7ee** [pomf/pomf#69]
:/

**Comment by Beyarz** [comment]
Is there any alternative that is up?

**Comment by ewhal** [comment]
Pretty sure most are ded

**Comment by LolcatsV2** [comment]
Fixed with https://github.com/pomf/pomf/commit/ed9d9b2082d651af339e0eb9999c6c2ea37be228

**Comment by Beyarz** [comment]
The new demo is down @LolcatsV2 .
https://downforeveryoneorjustme.com/sugoi.vidyagam.es

**Comment by LolcatsV2** [comment]
That was the old demo. The new demo can be found at https://safe.moe/

**Comment by Beyarz** [comment]
Ah shit, my fault. I was looking at the old link.

**Comment by razoplite** [comment]
Hi I am pretty new on GitHub. I cloned this repository, then I would like to host this on GitHub webserver or any there place, it is possible? And where Do I run the "make "command to compile it?

**Comment by liilac** [comment]
Hello,

Glad to hear you’re interested in the project.

It’s not possible to host pomf on GitHub pages, or a similar service, if that’s what you had in mind.

Happy to help though.

By the sounds of it you’re new to a lot of the technologies involved, and are looking for help setting up pomf rather than hosting a public demo.

If that’s the case, could you create a new issue, for us to help you in? It helps the right people see your question, and prevents notification spam for those following this issue.

**Comment by razoplite** [comment]
Hello, many thanks for your answer! Actually I would like to have some web page like catbox.moe, you know, simple upload/delete/download a file over internet, maybe 2 bottoms (upload/download) and a list of files (.txt) uploaded on website, just it, what do you recommend? Rememeber I am pretty new in this area, but have som IT knowledge in others languages.

**Comment by LolcatsV2** [comment]
For instructions on how to set up a baseline pomf instance, see the following guide: https://catbox.moe/retard.html. You're more than welcome to add me on one of my Contact methods from Catbox if you're having trouble with any of the steps.

I'm going to be locking this issue thread since the issue itself has already been resolved, and Issues aren't meant for extended discussion of unrelated topics.
